version: "3"

services:
  app:
    container_name: nodejs-es6
    restart: always
    build: .
    ports:
      - '3031:3031'
    volumes:
      - .:/usr/src/app
    links:
      - mongo
  
  mongo:
    container_name: nodejs-es6-mongo
    image: mongo
    ports:
      - '27017:27017'